import {
  ArrowRight,
  BadgeCheck,
  Bot,
  Brain,
  Bug,
  Calculator,
  CalendarDays,
  Camera,
  ChartBarBig,
  Check,
  ClipboardList,
  CloudSun,
  Droplets,
  Eye,
  FileText,
  FlaskConical,
  Globe,
  Handshake,
  Heart,
  House,
  Landmark,
  Leaf,
  LogOut,
  MapPin,
  Menu,
  MessageSquare,
  Microscope,
  Moon,
  Package,
  PawPrint,
  Rocket,
  Save,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Star,
  Store,
  Sun,
  TestTubeDiagonal,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  Wrench,
  X,
} from 'lucide-react'

const iconMap = {
  alert: TriangleAlert,
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  bot: Bot,
  box: Package,
  brain: Brain,
  bug: Bug,
  calculator: Calculator,
  calendar: CalendarDays,
  camera: Camera,
  cart: ShoppingCart,
  chart: ChartBarBig,
  check: Check,
  clipboard: ClipboardList,
  cloudSun: CloudSun,
  close: X,
  community: Handshake,
  delivery: Truck,
  droplets: Droplets,
  eye: Eye,
  fileText: FileText,
  flask: FlaskConical,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  home: House,
  landmark: Landmark,
  leaf: Leaf,
  logout: LogOut,
  mapPin: MapPin,
  menu: Menu,
  messageSquare: MessageSquare,
  microscope: Microscope,
  moon: Moon,
  package: Package,
  paw: PawPrint,
  rocket: Rocket,
  save: Save,
  search: Search,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  sprout: Sprout,
  star: Star,
  store: Store,
  sun: Sun,
  testTube: TestTubeDiagonal,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  truck: Truck,
  user: User,
  wheat: Sprout,
  wrench: Wrench,
}

export default function IconGlyph({
  name,
  size = 24,
  className = '',
  strokeWidth = 1.8,
}) {
  const Icon = iconMap[name]

  if (!Icon) return null

  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
    />
  )
}
